### ISSUE TITLE
Question: Compatibility with AWS Lambda SnapStart

### ISSUE THREAD

**Issue by pmeinhardt** [tink-crypto/tink-java#13]
Heya. 👋🙂 

First of all, thanks a ton for creating and maintaining Tink. ❤️ 

It saves me headaches and gives me better peace of mind, working on projects that require cryptography.

I was wondering whether there is any "official" information about using Tink (Java) in the context of pre-initialized VM snapshots, in particular starting multiple execution environments from the same snapshot.

For instance, using Tink with AWS Lambda SnapStart would be such a case:
https://docs.aws.amazon.com/lambda/latest/dg/snapstart-uniqueness.html

I've seen that AWS Lambda takes care of re-initializing `java.security.SecureRandom`, `/dev/random` and `/dev/urandom`. I was wondering though whether you are aware of any other pitfalls that might occur when using Tink in such an environment.

Do you know of any Tink APIs which would require explicit re-initialization?

Looking forward to hearing from you.
Thank you so much. 🙇 

Paul

---

As a final thought, maybe it'd be worth throwing something like this SpotBug plugin at Tink Java to try and detect potential issues with using Tink in resumed VM snapshots:
https://github.com/aws/aws-lambda-snapstart-java-rules

**Comment by tholenst** [comment]
As far as i can tell, any issue here would also be a vulnerability under a fork/vm-clone attack.

The only issue in this regard is with StreamingAead: https://developers.google.com/tink/issues/fork-safety.

If there are other cases of this, we plan to also communicate this on https://developers.google.com/tink/issues

Of course, you need to be aware that any key material is stored in your snapshot.
