### ISSUE TITLE
Vulnerability in older version, and cannot use newer version due to missing/removed class

### ISSUE THREAD

**Issue by ber4444** [tink-crypto/tink-java#15]
**Help us help you**

We'd like to know more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Describe the bug:**

DataTheorem scans reported a "Weak ECB Mode Used for Symmetric Encryption" finding in:
```
De-Obfuscated class: com.google.crypto.tink.subtle.EngineWrapper$TCipher
```
Additional information given by DT:
Using ECB as the mode of operation for AES encryption can leak information about the content of the encrypted data, because identical plaintext blocks are encrypted into identical ciphertext blocks. Consequently, ECB does not hide data patterns well and does not provide proper message confidentiality; this is demonstrated in the screenshot which shows how patterns can leak information about the plaintext.

As a consequence, ECB mode is not recommended for use in cryptographic protocols at all.

As raw cryptographic algorithms are difficult to use securely due to subtle implementation flaws such as weak modes of operation or timing attacks, avoid directly using low-level cryptographic APIs (such as javax.crypto.Cipher) to encrypt sensitive data.

**What was the expected behavior?**

We need to fix the security issue and it does seem to be resolved by upgrading:
```
- tink =  "com.google.crypto.tink:tink-android:1.8.0"
+ tink =  "com.google.crypto.tink:tink:1.11.0"
```
However, as you can see `tink-android` isn't available in the upgraded version.
We get duplicate class errors if we use both.

Now the problem is that `androidx.security.crypto.EncryptedSharedPreferences` still relies on classes from `tink-android`, so we get runtime errors like `Failed resolution of: Lcom/google/crypto/tink/integration/android/AndroidKeysetManager$Builder` when trying to use the new version as such:
```
implementation(libs.androidxCrypto) {
       exclude(group = "com.google.crypto.tink", module = "tink-android")
    }
```

**How can we reproduce the bug?**

See above

**Do you have any debugging information?**

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/crypto/tink/integration/android/AndroidKeysetManager$Builder;
                         E      at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:165)
                         E      at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:130)
```

**What version of Tink are you using?**

See above

**Can you tell us more about your development environment?**

JDK 17 and Android

**Is there anything else you'd like to add?**

It seems like publishing a 1.11.0 version of `tink-android` would resolve the issue.

**Comment by ber4444** [comment]
cross-posted to https://issuetracker.google.com/issues/309086850

**Comment by morambro** [comment]
Thanks for pointing this out! Something went wrong during the release of 1.11, now `tink-android 1.11` should be available: https://repo1.maven.org/maven2/com/google/crypto/tink/tink-android/1.11.0.

**Comment by ber4444** [comment]
Actually I'm still getting this reported by our infosec tool, and I see in your source you suppressed a warning for it:
https://github.com/tink-crypto/tink-java/blob/405a2912b38fdf6948fba96eb3047b5fc475b0bf/src/main/java/com/google/crypto/tink/subtle/EngineWrapper.java#L41

So `com.google.crypto.tink.subtle.EngineWrapper$TCipher` is still reported as "Weak ECB Mode Used for Symmetric Encryption
As raw cryptographic algorithms are difficult to use securely due to subtle implementation flaws such as weak modes of operation or timing attacks, avoid directly using low-level cryptographic APIs (such as javax.crypto.Cipher) to encrypt sensitive data."

I see ECB referenced in a couple of places in your code, not exactly sure if the use of Cipher, the use of ECB, or both are triggering this infosec report.
