### ISSUE TITLE
KmsClientsTestUtil not included in Maven artifact

### ISSUE THREAD

**Issue by SanjayVas** [tink-crypto/tink-java#19]
**Describe the bug:**

`com.google.crypto.tink:tink` Maven artifact does not provide `com.google.crypto.tink.KmsClientsTestUtil`

**What was the expected behavior?**

The above Maven artifact (or some separate testing artifact in `com.google.crypto.tink`) provides the aforementioned symbol.

**How can we reproduce the bug?**

In a Kotlin file that depends on the `com.google.crypto.tink:tink` Maven artifact:

```kotlin
import com.google.crypto.tink.KmsClientsTestUtil
```

**Do you have any debugging information?**

```
error: unresolved reference: KmsClientsTestUtil
import com.google.crypto.tink.KmsClientsTestUtil
                              ^
```

**What version of Tink are you using?**

1.7.0

**Can you tell us more about your development environment?**

Kotlin 1.8, JDK 11, Bazel 6.4.0

**Is there anything else you'd like to add?**

We're attempting to switch from depending on Tink as a Bazel project to depending on the Maven artifact. We depend on KmsClientsTestUtil in our tests.

**Comment by juergw** [comment]
I'll close this now. I don't think we should add this to the Maven artifact.
