### ISSUE TITLE
FIPS release

### ISSUE THREAD

**Issue by ber4444** [tink-crypto/tink-java#25]
**Help us help you**

Tell us more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Is your feature request related to a problem?**

I am facing [this issue](https://issuetracker.google.com/issues/324946007) using `com.google.crypto.tink:tink-android:1.12.0` and I believe a FIPS compatible binary would resolve this.

There are also other vulnerabilities like hardcoded crypto encryption in `com.google.crypto.tink.subtle.AesEaxJce`, which would be dead code and resolved with FIPS based on https://github.com/tink-crypto/tink-java/blob/e079e833f86e21cd619b93887954a5773991144b/src/main/java/com/google/crypto/tink/aead/AeadConfig.java#L140

**What sort of feature would you like to see?**

Describe your feature request. Or, how can we help solve the problem you noted above?

[This page](https://developers.google.com/tink/FIPS) states FIPS is only supported for C++ but I see relevant code in the Java repo

**Have you considered any alternative solutions?**

Use Facebook Conceal

**Would you like to add additional context?**

Vulnerability reports from a DAST tool

**Comment by tholenst** [comment]
I commented on the linked bug. Let me know if there are more issues.

**Comment by ber4444** [comment]
Thanks, can we have documentation about creating a FIPS build for Java?

**Comment by tholenst** [comment]
Tink doesn't need any special instructions. You can call TinkFips.restrictToFips(); in your binary as a first thing to make Tink try to do its best to ensure FIPS compliance.

You need to have conscrypt installed though, and it needs to be new enough and be built in fips compliant mode. I don't know how that works. Tink tries to fail if conscrypt isn't in the correct mode.

**Comment by uszeiss** [comment]
[This old comment on the mailing list](https://groups.google.com/g/tink-users/c/gZGSi8oJJzU/m/7tSgudWgBQAJ) implies that, for Java, using Tink + the FIPS-certified version of Bouncy Castle could also be FIPS-compliant.

Is Bouncy Castle still considered a viable alternative to Conscrypt as a Java security provider? From what I have seen in the Tink source code, the FIPS-related checks rely on the availability of Conscrypt.
