### ISSUE TITLE
Allow deterministic AEAD encryption with all active keys in keyset

### ISSUE THREAD

**Issue by thelateperseus** [tink-crypto/tink-java#35]
**Is your feature request related to a problem?**

We store secret data in an SQL database column encrypted with `DeterministicAead`. There is a database index on the encrypted column, allowing for efficient queries. When a new key is added to the keyset and promoted to the primary key, the database will eventually contain some data encrypted with the old key, and some data be encrypted with the new key. This means that database queries on the encrypted value may not return the expected result.

Example:
1. Database row is inserted with a plaintext value A encrypted with the old key.
2. A new key is added to the key set and is promoted to be the primary key.
3. A query runs `SELECT * FROM example_table WHERE encrypted_column = ?` and passes in the result of encrypting A using `DeterministicAead.encryptDeterministically()`
4. The row from step 1 is not returned because the encrypted value is different, even though the plaintext is the same.

Users need to be able to perform this search when they know the plaintext (e.g. account number or tax identifier).

**What sort of feature would you like to see?**

Add a new method to `DeterministicAead` as below:

```java
    public List<byte[]> encryptDeterministicallyWithAllEnabledKeys(
        final byte[] plaintext, final byte[] associatedData)
```

This method returns a list of encrypted values, one encrypted value per enabled key in the key set.

The query above can then be amended to `SELECT * FROM example_table WHERE encrypted_column IN (?,?)` and both encrypted values passed in.

**Have you considered any alternative solutions?**

An alternative solution would be to use a regular `Aead` instead of `DeterministicAead` for the values in `encrypted_column` and add another column `mac_column` containing the HMAC of the plaintext. A new database index would be created on `mac_column`, and the SQL queries would use `mac_column` instead of `encrypted_column`.

However, this just introduces additional complexity without improving security. Searching on multiple values is still required in this scenario when multiple keys in the keyset are active. We'd still need to add a similar method to the `MacPrimitive` interface to satisfy this searching requirement.

**Would you like to add additional context?**

We have implemented this functionality ourselves by creating a class that relies on `PrimitiveSet` and `Registry.registerPrimitiveWrapper`. These have now been removed from Tink's public API as of v1.13.0, so our code now relies on classes in `com.google.crypto.tink.internal`.

I'm happy to submit a pull request based on our code if the Tink team are happy with this concept.

**Comment by tholenst** [comment]
We will not change the API of DeterministicAead.

Instead, what you need to do is to use the KeysetHandle.Builder to split your keyset into multiple keysets, one per key. Then you can call "GetPrimitive" on each of them.

To split the keyset, you call KeysetHandle.importKey and put the result into a KeysetHandle.Builder.

Let me know if you have trouble.

**Comment by thelateperseus** [comment]
@tholenst thanks for the suggestion. I've implemented successfully as per below.

```java
      final KeysetHandle keysetHandle; // loaded from JSON
      final Set<DeterministicAead> singleKeyDeterministicAeads = new LinkedHashSet<>();
      for (int i = 0; i < keysetHandle.size(); ++i) {
        final Entry keyEntry = keysetHandle.getAt(i);
        if (keyEntry.getStatus() == KeyStatus.ENABLED) {
          final KeysetHandle singleKeyKeysetHandle =
              KeysetHandle.newBuilder()
                  .addEntry(KeysetHandle.importKey(keyEntry.getKey()).makePrimary())
                  .build();
          singleKeyDeterministicAeads.add(
              singleKeyKeysetHandle.getPrimitive(DeterministicAead.class));
        }
      }
```

**Comment by thelateperseus** [comment]
Closing issue
